### ISSUE TITLE
Update documentation and upload live example

### ISSUE THREAD

**Issue by ghost** [AirConsole/airconsole-construct2#6]
I've been working with this plugin for a number of hours now and I've yet to create anything functional. There are a number of factors making it difficult for me to determine exactly why this is and I think those could be mitigated by updating the [C2 plugin documentation](http://developers.airconsole.com/#/guides/construct2) and providing a live, online build of the Pong example made with Construct 2.

It seems as though the documentation hasn't been updated since v1.1. I haven't explored it in great detail since I'd like to get the Pong example working before I start porting my own game to Airconsole, but I've noticed a few out of date things and would appreciate the whole thing being looked over once again.

Simply building the included Pong example and trying to run it in the simulator seems like it should work without issue, and yet I see a number of errors in the Chrome dev console and my paddles never seem to spawn (implying that the controllers aren't connecting). I would really appreciate an example build hosted online that I can run through the simulator and see how a working build should look. It would be nice to compare dev console logs between my build and the working build to see what errors (if any) are my fault.

**Comment by francois-dibulo** [comment]
Thanks for your input again! An update of the documentation is on top of our todo-list.

Can you paste your log or the errors you get?!

**Comment by ghost** [comment]
`Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`

I don't think this is an issue, but I commonly see this error. There were a few more about http vs https resources that I managed to get rid of by editing some references (I forget where, I think it was in the screen and/or controller files).

`Uncaught TypeError: this.Nd.Ts is not a function`

This error comes up consistently and is always the last to show up, so I think it may be where the game is getting choked up.

**Comment by francois-dibulo** [comment]
Can you try to upload your game on: http://airconsole.com/developers
You should not get any https conflict errors then (except when you still load external files through https)
Or is your game somewhere hosted? So that I can check myself?

No idea though what `this.Nd.Ts` could be oO

**Comment by ghost** [comment]
Here's my build of the pong example:

https://dl.dropboxusercontent.com/u/1108862/Testing/airconsole_pong/

It's worth noting that I was getting variations of that `this.Nd.Ts` (as in, the `Nd.Ts` part would be different letters) when working on my own game as well.

**Comment by francois-dibulo** [comment]
I just uploaded the pong example myself to our servers:
http://www.airconsole.com/simulator/#http://com.demo.construct.cdn.airconsole.com/2015-12-08-16-01-44/
and it works without problems. I also don't have problem with `this.Nd.Ts`.
Can your try to put it on: http://airconsole.com/developers ?!

**Comment by francois-dibulo** [comment]
oh wait ... forgot to set 1.3.0 :)

**Comment by francois-dibulo** [comment]
Nope, also works with 1.3.0:
http://www.airconsole.com/simulator/#http://com.demo.construct.cdn.airconsole.com/2015-12-08-16-11-01/

**Comment by ghost** [comment]
How do I actually upload the game files? I don't see any options for that here.

![airconsoleUpload.png](https://dl.dropboxusercontent.com/u/1108862/Images/airconsoleUpload.PNG)

**Comment by francois-dibulo** [comment]
Yeah thats a bit confusing - will fix that soon. Just fill out the form and then click update.

After that you can upload a .zip file of your root dir (where screen.html and controller.html) are in.

You will also have to upload a cover art, you can use this for so far:

![unnamed](https://cloud.githubusercontent.com/assets/12541790/11661153/b9d0d09a-9dd0-11e5-9e54-d5d7078d001b.jpg)

**Comment by ghost** [comment]
I get that same error even after uploading: 

http://www.airconsole.com/simulator/#http://com.virtuallycompetent.pong.cdn.airconsole.com/2015-12-08-16-29-38/

Is something wrong with the way I'm exporting from Construct?

**Comment by ghost** [comment]
@francois-n-dream Any updates on this issue?

**Comment by francois-dibulo** [comment]
Sorry, we are having a major release today and did not really have time to look into it again.
However, my plan is to rebuild the whole pong example again and check if that still works.
I guess you did not change anything in the pong project example?!

**Comment by ghost** [comment]
Nope, no changes. I had so much trouble with my personal project that I just wanted to see a working example, so I tried Pong without any modifications, but it still didn't work.

I'm using r216 of Construct 2 Personal Edition (64-bit) if any of that information is helpful. I don't remember seeing anything in the changelog that sounds like it would have broken anything on your plugin, but that's the only thing I can think of right now that might be different between us.

Let me know if there's any further information I can provide to help resolve this issue.

**Comment by joannesalfa** [comment]
I have this issue, I gave up making an awesome horror game with airconsole with 1 month of development but I'm ended up with runtime errors because of this plugin, so there no way to publish my game before deadline, however I didn't give up for this game so I cannot enter this contest, will post more details when I get my home (Im busy at office) and eventually will publish game in January.

Also I have ideas that plugin needs improvement to make nice workflow between controller and screen.
But I've contacted to airconsole staff team about directory update, I don't like to upload one directory with screen.html and controller.html togheter because it can confuse which is file such as data.js to upload, my suggestion was making new directories such as folders like screen/ and controller/ it would help us to prevent problems. Actually, they didn't response me yet.

**Comment by ghost** [comment]
Thanks for chiming in, @joannesalfa, it's nice to know I'm not alone in this issue.

I'm looking to port an existing game I have to Airconsole, so I'm optimistic that I can complete that process in just a few days before the contest deadline...of course, that means I need a working plugin in the next day or two. :smile:

**Comment by francois-dibulo** [comment]
I just remarked that your export is with a minimized c2runtime and mine not. Can you try an export without?

**Comment by francois-dibulo** [comment]
Ok, I tried myself and now I also get the same error. Please try it :)!

**Comment by ghost** [comment]
@francois-n-dream Nice catch! I exported the Pong example without minifying and it threw no errors (at least not the show stopping errors). I still had to edit two lines in the controller file for it to actually function properly, though. I changed the jQuery reference to `https` instead of `http` and made the second line reference the local Airconsole script instead of pulling it from the web (and also changed it to be v1.3.0 instead of v1.2.1). The following are the edited lines:

`<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>`
`<script type="text/javascript" src="airconsole-1.3.0.js"></script>`

I tried my personal project as well and it still doesn't seem to function properly, but at least it isn't throwing any errors. I suppose the race is on to submit before the contest deadline!

**Comment by Psychokiller1888** [comment]
Exemple project was updated and pushed to master, in both version 1 and version 2
